version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: echo "$DOCKER_PASS" | docker login --username DOCKER_USER --password-stdin
     - run: docker build -t .
     - run: docker push chfanghr/cpp-dev:latest     