version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker login --username $DOCKER_USER --password $DOCKER_PASS
     - run: docker build -t .
     - run: docker push chfanghr/cpp-dev:latest     